<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-OSG6H8E" failures="0" tests="8" name="testng_practise.TestNG_key" time="2.125" errors="1" timestamp="2025-07-27T10:41:08 IST" skipped="1">
  <testcase classname="testng_practise.TestNG_key" name="CTest" time="0.020"/>
  <system-out/>
  <testcase classname="testng_practise.TestNG_key" name="TestA" time="0.010"/>
  <system-out/>
  <testcase classname="testng_practise.TestNG_key" name="TestB" time="0.008"/>
  <system-out/>
  <testcase classname="testng_practise.TestNG_key" name="TestB" time="0.012"/>
  <system-out/>
  <testcase classname="testng_practise.TestNG_key" name="TestB" time="0.007"/>
  <system-out/>
  <testcase classname="testng_practise.TestNG_key" name="TestE" time="0.011"/>
  <system-out/>
  <testcase classname="testng_practise.TestNG_key" name="TestF" time="2.057">
    <error message="Method testng_practise.TestNG_key.TestF() didn&#039;t finish within the time-out 2000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testng_practise.TestNG_key.TestF() didn't finish within the time-out 2000
at java.base@17.0.5/java.lang.Thread.sleep(Native Method)
at app//testng_practise.TestNG_key.TestF(TestNG_key.java:52)
at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- TestF -->
  <system-out/>
  <testcase classname="testng_practise.TestNG_key" name="TestD">
    <skipped/>
  </testcase> <!-- TestD -->
  <system-out/>
</testsuite> <!-- testng_practise.TestNG_key -->
